/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   amessage__init
                     (AMessage         *message)
{
  static const AMessage init_value = AMESSAGE__INIT;
  *message = init_value;
}
size_t amessage__get_packed_size
                     (const AMessage *message)
{
  assert(message->base.descriptor == &amessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t amessage__pack
                     (const AMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &amessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t amessage__pack_to_buffer
                     (const AMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &amessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AMessage *
       amessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AMessage *)
     protobuf_c_message_unpack (&amessage__descriptor,
                                allocator, len, data);
}
void   amessage__free_unpacked
                     (AMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &amessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const Status amessage__status__default_value = STATUS__SUCCESS;
static const CmdType amessage__type__default_value = CMD_TYPE__COMMAND;
static const Cmd amessage__cmd__default_value = CMD__NONE;
static const ProtobufCFieldDescriptor amessage__field_descriptors[5] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AMessage, status),
    &status__descriptor,
    &amessage__status__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AMessage, type),
    &cmd_type__descriptor,
    &amessage__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AMessage, cmd),
    &cmd__descriptor,
    &amessage__cmd__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idx",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AMessage, idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(AMessage, n_data),
    offsetof(AMessage, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned amessage__field_indices_by_name[] = {
  2,   /* field[2] = cmd */
  4,   /* field[4] = data */
  3,   /* field[3] = idx */
  0,   /* field[0] = status */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange amessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor amessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AMessage",
  "AMessage",
  "AMessage",
  "",
  sizeof(AMessage),
  5,
  amessage__field_descriptors,
  amessage__field_indices_by_name,
  1,  amessage__number_ranges,
  (ProtobufCMessageInit) amessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue status__enum_values_by_number[8] =
{
  { "SUCCESS", "STATUS__SUCCESS", 0 },
  { "INVALID", "STATUS__INVALID", 1 },
  { "TOOMANY", "STATUS__TOOMANY", 2 },
  { "TIMEOUT", "STATUS__TIMEOUT", 3 },
  { "ESERVER", "STATUS__ESERVER", 4 },
  { "ECLIENT", "STATUS__ECLIENT", 5 },
  { "RECONNT", "STATUS__RECONNT", 6 },
  { "BRDINFO", "STATUS__BRDINFO", 7 },
};
static const ProtobufCIntRange status__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex status__enum_values_by_name[8] =
{
  { "BRDINFO", 7 },
  { "ECLIENT", 5 },
  { "ESERVER", 4 },
  { "INVALID", 1 },
  { "RECONNT", 6 },
  { "SUCCESS", 0 },
  { "TIMEOUT", 3 },
  { "TOOMANY", 2 },
};
const ProtobufCEnumDescriptor status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Status",
  "Status",
  "Status",
  "",
  8,
  status__enum_values_by_number,
  8,
  status__enum_values_by_name,
  1,
  status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue cmd_type__enum_values_by_number[4] =
{
  { "COMMAND", "CMD_TYPE__COMMAND", 0 },
  { "STREAM", "CMD_TYPE__STREAM", 1 },
  { "NOTIFY", "CMD_TYPE__NOTIFY", 2 },
  { "BRDCAST", "CMD_TYPE__BRDCAST", 3 },
};
static const ProtobufCIntRange cmd_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex cmd_type__enum_values_by_name[4] =
{
  { "BRDCAST", 3 },
  { "COMMAND", 0 },
  { "NOTIFY", 2 },
  { "STREAM", 1 },
};
const ProtobufCEnumDescriptor cmd_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CmdType",
  "CmdType",
  "CmdType",
  "",
  4,
  cmd_type__enum_values_by_number,
  4,
  cmd_type__enum_values_by_name,
  1,
  cmd_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue cmd__enum_values_by_number[12] =
{
  { "NONE", "CMD__NONE", 0 },
  { "PLAY", "CMD__PLAY", 1 },
  { "STOP", "CMD__STOP", 2 },
  { "PAUSE", "CMD__PAUSE", 3 },
  { "NEXT", "CMD__NEXT", 4 },
  { "PREV", "CMD__PREV", 5 },
  { "QUIT", "CMD__QUIT", 6 },
  { "SEEK", "CMD__SEEK", 7 },
  { "TIME", "CMD__TIME", 8 },
  { "URI", "CMD__URI", 9 },
  { "ACK", "CMD__ACK", 10 },
  { "CMD_COUNT", "CMD__CMD_COUNT", 11 },
};
static const ProtobufCIntRange cmd__value_ranges[] = {
{0, 0},{0, 12}
};
static const ProtobufCEnumValueIndex cmd__enum_values_by_name[12] =
{
  { "ACK", 10 },
  { "CMD_COUNT", 11 },
  { "NEXT", 4 },
  { "NONE", 0 },
  { "PAUSE", 3 },
  { "PLAY", 1 },
  { "PREV", 5 },
  { "QUIT", 6 },
  { "SEEK", 7 },
  { "STOP", 2 },
  { "TIME", 8 },
  { "URI", 9 },
};
const ProtobufCEnumDescriptor cmd__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Cmd",
  "Cmd",
  "Cmd",
  "",
  12,
  cmd__enum_values_by_number,
  12,
  cmd__enum_values_by_name,
  1,
  cmd__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
